import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';
import { BreakpointIndicator } from '@/components/shared/provider/BreakPoints';
import AppTheme from '@/components/shared/provider/AppTheme';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  preload: false, // Page initial render event fast ga aye process lo console warning rakunda chestadhi
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn('h-full', 'antialiased', 'font-sans', inter.variable)}
    >
      <body className="relative flex min-h-full flex-col">
        <AppTheme>{children}</AppTheme>
        <BreakpointIndicator />
      </body>
    </html>
  );
}
