<<<<<<< HEAD
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';
import { BreakpointIndicator } from '@/components/shared/provider/BreakPoints';
import AppTheme from '@/components/shared/provider/AppTheme';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  preload: false, // Page initial render event fast ga aye process lo console warning rakunda chestadhi
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> f8f9d381b405553a7e809ea9c45df5ce7bbb8e15
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
<<<<<<< HEAD
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
=======
      suppressHydrationWarning
      className={cn('h-full', 'antialiased', 'font-sans', inter.variable)}
    >
      <body className="relative flex min-h-full flex-col">
        <AppTheme>{children}</AppTheme>
        <BreakpointIndicator />
      </body>
>>>>>>> f8f9d381b405553a7e809ea9c45df5ce7bbb8e15
    </html>
  );
}
